services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: gw2packrat
      POSTGRES_USER: gw2packrat
      POSTGRES_PASSWORD: gw2packrat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
